### ISSUE TITLE
LocalFileSystem: fail to open "cnn-ocr-symbol.json"

### ISSUE THREAD

**Issue by Builtor** [szad670401/end-to-end-for-chinese-plate-recognition#14]
在Ubuntu16.04下，下载zip解压后，运行 python test.py 报错：
python test.py 
(30, 120, 3)
(3, 30, 120)
[18:02:27] include/dmlc/logging.h:235: [18:02:27] src/io/local_filesys.cc:154: Check failed: allow_null  LocalFileSystem: fail to open "cnn-ocr-symbol.json"
Traceback (most recent call last):
  File "test.py", line 84, in <module>
    TestRecognizeOne(cv2.imread("./plate/01.jpg"))
  File "test.py", line 59, in TestRecognizeOne
    _, arg_params, __ = mx.model.load_checkpoint("cnn-ocr", 1)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/model.py", line 372, in load_checkpoint
    symbol = sym.load('%s-symbol.json' % prefix)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/symbol.py", line 971, in load
    check_call(_LIB.MXSymbolCreateFromFile(c_str(fname), ctypes.byref(handle)))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [18:02:27] src/io/local_filesys.cc:154: Check failed: allow_null  LocalFileSystem: fail to open "cnn-ocr-symbol.json"
PIL我安装的是pillow，python版本2.7，请问是哪一步出现问题了呢？

**Comment by Builtor** [comment]
好吧，我跑一遍train.py后便有了json文件。。。

**Comment by ZoeShaw101** [comment]
请问为什么我跑trian.py 也有问题呢？
$ python train.py
[Deprecation Warning] mxnet.model.FeedForward has been deprecated. Please use mxnet.mod.Module instead.
start
start
[17:34:35] src/operator/tensor/./matrix_op-inl.h:156: Using target_shape will be deprecated.
2017-04-19 17:34:35,312 Start training with [cpu(0)]
[17:34:35] src/operator/tensor/./matrix_op-inl.h:156: Using target_shape will be deprecated.
[17:34:35] src/operator/tensor/./matrix_op-inl.h:156: Using target_shape will be deprecated.
非法指令 (核心已转储)
