### ISSUE TITLE
How can I solve the mistake，thanks

### ISSUE THREAD

**Issue by leihentulong** [szad670401/end-to-end-for-chinese-plate-recognition#7]
[16:28:34] ./dmlc-core/include/dmlc/logging.h:208: [16:28:34] src/io/local_filesys.cc:149: Check failed: allow_null  LocalFileSystem: fail to open "cnn-ocr-symbol.json"
Traceback (most recent call last):
  File "/opt/github/end-to-end-for-chinese-plate-recognition/test.py", line 84, in <module>
    TestRecognizeOne(cv2.imread("./plate/01.jpg"))
  File "/opt/github/end-to-end-for-chinese-plate-recognition/test.py", line 59, in TestRecognizeOne
    _, arg_params, __ = mx.model.load_checkpoint("cnn-ocr", 1)
  File "/usr/local/lib/python2.7/site-packages/mxnet/model.py", line 437, in load_checkpoint
    symbol = sym.load('%s-symbol.json' % prefix)

**Comment by leihentulong** [comment]
label = mx.symbol.transpose(data = label)
AttributeError: 'module' object has no attribute 'transpose'

**Comment by leihentulong** [comment]
two version.uninstall the old.
